require('settings')
require('packages')
require('lualine').setup()
require("mason").setup()
require("mason-lspconfig").setup()
require('onedark').load()

local lsp = require('lsp-zero')
lsp.preset('recommended')
lsp.setup()
